-- Create movies table in Supabase
-- Run this in your Supabase SQL Editor

CREATE TABLE IF NOT EXISTS movies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tmdb_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    media_type TEXT NOT NULL DEFAULT 'movie', -- 'movie' or 'tv'
    season_number INTEGER,
    episode_number INTEGER,
    doodstream_url TEXT,
    doodstream_download_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(tmdb_id, media_type, season_number, episode_number)
);

-- Enable Row Level Security (optional, for security)
ALTER TABLE movies ENABLE ROW LEVEL SECURITY;

-- Allow public read access (adjust as needed for your security requirements)
CREATE POLICY "Allow public read access" ON movies FOR SELECT USING (true);

-- Allow public insert/update (adjust as needed for your security requirements)
CREATE POLICY "Allow public insert" ON movies FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON movies FOR UPDATE USING (true);

-- Create index on tmdb_id for faster lookups
CREATE INDEX IF NOT EXISTS idx_movies_tmdb_id ON movies(tmdb_id);

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger to automatically update updated_at
CREATE TRIGGER update_movies_updated_at BEFORE UPDATE ON movies
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
