-- Create movies and TV episodes tables in Supabase
-- Run this in your Supabase SQL Editor

-- Movies table
CREATE TABLE IF NOT EXISTS movies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tmdb_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    year INTEGER,
    doodstream_url TEXT,
    doodstream_download_url TEXT,
    playmogo_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(tmdb_id)
);

-- TV Episodes table
CREATE TABLE IF NOT EXISTS tv_episodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tmdb_id INTEGER NOT NULL,
    series_title TEXT NOT NULL,
    season_number INTEGER,
    episode_number INTEGER NOT NULL,
    title TEXT,
    doodstream_url TEXT,
    doodstream_download_url TEXT,
    playmogo_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(tmdb_id, season_number, episode_number)
);

-- Enable Row Level Security (optional, for security)
ALTER TABLE movies ENABLE ROW LEVEL SECURITY;
ALTER TABLE tv_episodes ENABLE ROW LEVEL SECURITY;

-- Allow public read access for movies
CREATE POLICY "Allow public read access" ON movies FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON movies FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON movies FOR UPDATE USING (true);

-- Allow public read access for tv_episodes
CREATE POLICY "Allow public read access episodes" ON tv_episodes FOR SELECT USING (true);
CREATE POLICY "Allow public insert episodes" ON tv_episodes FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update episodes" ON tv_episodes FOR UPDATE USING (true);

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_movies_tmdb_id ON movies(tmdb_id);
CREATE INDEX IF NOT EXISTS idx_tv_episodes_tmdb_id ON tv_episodes(tmdb_id);
CREATE INDEX IF NOT EXISTS idx_tv_episodes_series ON tv_episodes(tmdb_id, season_number);

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Triggers to automatically update updated_at
CREATE TRIGGER update_movies_updated_at BEFORE UPDATE ON movies
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_tv_episodes_updated_at BEFORE UPDATE ON tv_episodes
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
