-- Add a dedicated home for TV series episodes in Supabase.
-- Run this in the SQL Editor:
--   https://supabase.com/dashboard/project/smujmccdavjucdtwnqgt/editor
--
-- After this runs, TV episodes get their own table and the bot
-- (catalog.save_episode_to_supabase) will insert into it automatically.

-- 1) The dedicated TV table
CREATE TABLE IF NOT EXISTS tv_episodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tmdb_id INTEGER NOT NULL,
    series_title TEXT NOT NULL,
    season_number INTEGER,
    episode_number INTEGER NOT NULL,
    title TEXT,
    filecode TEXT,
    doodstream_url TEXT,
    doodstream_download_url TEXT,
    playmogo_url TEXT,
    vidsrc_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(tmdb_id, season_number, episode_number)
);

-- 2) Row Level Security + public access policies
ALTER TABLE tv_episodes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "tv_public_read" ON tv_episodes;
CREATE POLICY "tv_public_read" ON tv_episodes FOR SELECT USING (true);

DROP POLICY IF EXISTS "tv_public_insert" ON tv_episodes;
CREATE POLICY "tv_public_insert" ON tv_episodes FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "tv_public_update" ON tv_episodes;
CREATE POLICY "tv_public_update" ON tv_episodes FOR UPDATE USING (true);

DROP POLICY IF EXISTS "tv_public_delete" ON tv_episodes;
CREATE POLICY "tv_public_delete" ON tv_episodes FOR DELETE USING (true);

-- 3) Fast lookups
CREATE INDEX IF NOT EXISTS idx_tv_episodes_series ON tv_episodes(tmdb_id, season_number);
CREATE INDEX IF NOT EXISTS idx_tv_episodes_tmdb ON tv_episodes(tmdb_id);

-- 4) One-time migration: move the existing TV rows out of the movies table
INSERT INTO tv_episodes (tmdb_id, series_title, season_number, episode_number, title, doodstream_url, doodstream_download_url)
SELECT
    tmdb_id,
    regexp_replace(title, '\s+[Ss]\d+[Ee]\d+.*$', '') AS series_title,
    season_number,
    episode_number,
    title,
    doodstream_url,
    doodstream_download_url
FROM movies
WHERE media_type = 'tv'
ON CONFLICT (tmdb_id, season_number, episode_number) DO NOTHING;

-- 5) Clean the shows out of the movies table now that they have a dedicated home
DELETE FROM movies WHERE media_type = 'tv';

-- 6) Keep updated_at fresh
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_tv_episodes_updated_at ON tv_episodes;
CREATE TRIGGER update_tv_episodes_updated_at BEFORE UPDATE ON tv_episodes
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();